### ISSUE TITLE
cgo compile error when trying to build with go-jack as dependency

### ISSUE THREAD

**Issue by Pieterv24** [xthexder/go-jack#20]
When I try to build the example/passthrough.go file.
I get the following error:
```
# github.com/xthexder/go-jack
_cgo_export.c: In function ‘goPortRegistration’:
_cgo_export.c:81:38: error: parameter name omitted
   81 | void goPortRegistration(GoUint port, GoInt register, void* arg)
      |                                      ^~~~~~~~~~~~~~
_cgo_export.c:90:14: error: expected expression before ‘register’
   90 |  _cgo_a.p1 = register;
      |              ^~~~~~~~
```

I've installed go-jack using `go get github.com/xthexder/go-jack`
And tried building the passthough file using the makefile and using `go-jack`

My specs are:
OS: Arch Linux
Kernel: 5.7.12-arch1-1
Jackd Version: 1.9.14
Go version: 1.15

**Comment by xthexder** [comment]
It's a little hard to say what's going on here. I haven't made any changes to this project in a while.

cgo might be complaining because `register` is a reserved keyword in C/C++. Either that or something changed with the cgo types like `GoInt`, but that seems unlikely.

I don't have my go-jack dev environment set up at the moment, but you could try renaming `register` something else that's not a keyword like `registered`

**Comment by Pieterv24** [comment]
That does look like it fixed the compilation problem.
I'm however still having issues actually running it.

Logs:
```
Go Passthrough
SuspendRefNum error
JackClient::Execute error name = Go Passthrough
Shutting down
Server is not running
```

Ill try and see if I can fix it.
Ideas as to what I might be doing wrong are appreciated.

**Comment by tgirod** [comment]
Same here, curious to see if you find a solution !

**Comment by alangecker** [comment]
got the same problem.
Switching back to go 1.14 solved it for now.

**Comment by boomlinde** [comment]
I've addressed the original issue in my pull request. @Pieterv24, are you able to run other Jack clients? After applying my change, I am able to build and run the pass-through example without issue.
